blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions
    url: https://github.com/uzibiton/automation-interview-pre/discussions
    about: Ask questions or discuss ideas with the community
